import ReservationContextProvider from "@/Providers/ReservationContext.provider";

import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

import { cn } from "@/lib/utils";
import { ReactQueryProvider } from "@/Providers/ReactQuery";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
        style={{ background: "#343A40" }}
      >
        <Toaster />
        <ReactQueryProvider>
          <ReservationContextProvider>
            {children}
          </ReservationContextProvider>
        </ReactQueryProvider>

      </body>
    </html>
  );
}
